# Configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directories: 
    - "/"
    - "/gradle-plugin-integration-tests"
    - "/examples/gradle-google-ksp"
    schedule:
      interval: "daily"
    # Ignoring
    ignore:
      # Kotlin majority updates
      - dependency-name: "org.jetbrains.kotlin*"
        update-types: [ "version-update:semver-major" ]
    labels:
      - "dependencies"

  - package-ecosystem: "maven"
    directories:
      - "/examples/maven-ksp"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
