[versions]
agp = "8.10.1"
detekt = "2.0.0-alpha.2"
dokka = "2.1.0"
jackson = "2.18.5" # pin it
junit = "6.0.2"
junit-pioneer = "2.3.0"
koog = "0.6.1"
kotest = "6.1.3"
kotlin = "2.2.21"
kotlinxSerialization = "1.8.1"
kover = "0.9.6"
ksp = "2.3.5"
langchain4j = "1.11.0"
logging = "7.0.14"
mockk = "1.14.9"
slf4j = "2.0.17"
vanniktechMavenPublish = "0.36.0"

[libraries]
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "logging" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktechMavenPublish" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
koog-agents-tools = { module = "ai.koog:agents-tools", version.ref = "koog" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
langchain4j-core = { module = "dev.langchain4j:langchain4j-core", version.ref = "langchain4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

ksp-symbol-processing-api = {module ="com.google.devtools.ksp:symbol-processing-api", version.ref="ksp"}
ksp-symbol-processing-aa-embeddable = {module ="com.google.devtools.ksp:symbol-processing-aa-embeddable", version.ref="ksp"}
ksp-symbol-processing-common-deps = {module ="com.google.devtools.ksp:symbol-processing-common-deps", version.ref="ksp"}

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }