[versions]
koog = "0.6.1"
kotest = "6.1.3"
kotlinxSerialization = "1.10.0"
ksp = "2.3.5"
kotlin = "2.3.0"

[libraries]
koog-agents-tools = { module = "ai.koog:agents-tools", version.ref = "koog" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }