name: Examples

on:
  merge_group:
  push:
    branches: [ "main" ]
    paths:
      - "examples/**"
      - ".github/workflows/examples.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'temurin'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  gradle-examples:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        example:
          - gradle-google-ksp

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          add-job-summary-as-pr-comment: on-failure
          cache-cleanup: always

      - name: "Build Sample: ${{ matrix.example }}"
        working-directory: ./examples/${{ matrix.example }}
        run: ./gradlew --no-daemon clean build --rerun-tasks

      - name: Upload Reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: reports-${{ matrix.example }}
          path: |
            ./examples/${{ matrix.example }}/build/reports/

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: ./examples/${{ matrix.example }}/build/test-results/**/TEST-*.xml
          annotate_only: true
          detailed_summary: true
          flaky_summary: true
          include_empty_in_summary: false
          include_time_in_summary: true


  maven-examples:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        example:
          - maven-ksp

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: "Build Sample: ${{ matrix.example }}"
        working-directory: ./examples/${{ matrix.example }}
        run: mvn -B clean package

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: ./examples/${{ matrix.example }}/target/*-reports/TEST-*.xml
          annotate_only: true
          detailed_summary: true
          flaky_summary: true
          include_empty_in_summary: false
          include_time_in_summary: true
